### ISSUE TITLE
MsgResTonpy.trans - grammar

### ISSUE THREAD

**Issue by ObiKKa** [cjuub/okaeri-chibi-translation#19]
Looks like you've missed the comment I added on after my latest correct commit in [ObiKKa:patch-12](https://github.com/cjuub/okaeri-chibi-translation/pull/18) that you pulled in.

It says:

> Does line #758 need a 'you' or 'he', for example in between 'then' and 'won't...'?

The line is:

> If the House-Watts are empty<N>then <1a06ff000003>won't be able to use<1a06ff00000d><N>the Chibi-Vacuum.

**Comment by cjuub** [comment]
You are correct! Thanks!

Actually, the sentence was not even properly translated, it's correct now. :)

**Comment by ObiKKa** [comment]
Added your [commit page](https://github.com/cjuub/okaeri-chibi-translation/commit/969fcb88bd168b0a17bc27b4396f36f5cf0f01b9) for reference.
