### ISSUE TITLE
MsgResTonpy.trans - incomplete sentence?

### ISSUE THREAD

**Issue by ObiKKa** [cjuub/okaeri-chibi-translation#20]
Lines #394 and #395 of the [MsgResTonpy.trans](https://github.com/cjuub/okaeri-chibi-translation/blob/master/text_translated/MsgResTonpy.trans#L394) file looks incomplete with no words in between several <> tags. Am I right?

**Comment by cjuub** [comment]
It's because Chibi-Robo is too far away and can't make out all the words being said. It's correct.
