### ISSUE TITLE
MsgResTonpy.trans - Menu location problem?

### ISSUE THREAD

**Issue by ObiKKa** [cjuub/okaeri-chibi-translation#21]
When I saw this line #709 at the [MsgResTonpy.trans](https://github.com/cjuub/okaeri-chibi-translation/blob/master/text_translated/MsgResTonpy.trans#L709) file I wasn't sure if you'd stated it right.

> Go ahead and use the Chibi-Eyes from the top right <1a06ff000003>Chibi-Menu<1a06ff00000d>.

Does it mean the 'top right _corner of the_ Chibi-Menu'? Or is it a sub-menu in the top-right area among other Chibi-Menus?

**Comment by cjuub** [comment]
It refers to the Chibi-Menu in the top right corner of the screen. It does feel a bit weird saying only "top right", but it kinda works. I'll see if I can reformulate it.
