### ISSUE TITLE
MsgResAca.trans - 2 adjacent similar looking lines?

### ISSUE THREAD

**Issue by ObiKKa** [cjuub/okaeri-chibi-translation#24]
Regarding the first script file that we both just proofread let's look at lines [301 and 302](https://github.com/cjuub/okaeri-chibi-translation/blob/master/text_translated/MsgResAca.trans#L301-L302). Are you sure you didn't almost repeat them ad verbatim, perhaps forgetting to replace the first line with the other line?

> Thanks to ya, I can now make bright red tomatoes again!
> Thanks to ya, I feel like I can make bright red tomatoes again!

**Comment by cjuub** [comment]
It's correct, they're very similar in Japanese too:
おかげで　また真っ赤なトマトが<N>できるようになったんだべ！
おかげで　また真っ赤なトマトが<N>できそうな気分なんだべ！

Just one of the two lines gets triggered depending on if Ketchup has made red tomatoes yet or not when you talk to him.
