### ISSUE TITLE
Oxford comma very early in game - Telly.

### ISSUE THREAD

**Issue by DangusTaargus** [cjuub/okaeri-chibi-translation#25]
I just started playing this, so thank you so much! This makes me so happy!

Anyway, I didn't get a chance to write down the line, but there's a part VERY early in the game, about the first time you go into your chibi house, where telly says something to you, and he doesn't use an oxford comma on a third statement right before the 'and'. I don't know the exact line, and I looked for it in the code but I couldn't find it so I'm sorry for that.

I know the oxford comma isn't necessarily an exact rule, but I find it reads a lot better when you have it included.

I'm sorry I can't be more specific, but I figured that you were likely more familiar with the lines, and you might know what I am talking about.

Thanks again.

**Comment by cjuub** [comment]
I'm sorry but I have no idea what line you are referring to. Most of Telly's lines are in:
`text_translated/MsgResTonpy.trans`
But it might also be in:
`text_translated/MsgResFamily.trans`
`text_translated/MsgResFamily2.trans`
`text_translated/MsgResFamily3.trans`

The lines are not in chronological order, so the fact that it happens early in the game does not help much.
I tried searching for "and" in Tonpy file, but did not find anything weird.

**Comment by DangusTaargus** [comment]
I'll start a new file and try to get to the line again. I'll get back to in a second.

**Comment by DangusTaargus** [comment]
Line 103 in text_translated/MsgResFamily.trans

The line right now is: "You can do things like vacuuming, throw away trash and so on..."

It would read better if it were: You can do things like vacuuming, throw away trash, and so on..."

As you have it, the implication without the oxford comma is that you can throw away trash as well as throw away 'so on' - it just kind of reads wrong and this is true of any similar sentences so hopefully there weren't too many. With the extra comma, the list of actions in the sentence is separated and clear.

In fact I would consider changing it further to: "You can do things like vacuum dust, throw away trash, and so on..."

Anything really... I find 'vacuuming' on it's own to read awkwardly. Anyway! Great work again. Hope this helps.

**Comment by cjuub** [comment]
I absolutely agree, thank you for contributing! This issue is now fixed.
