### ISSUE TITLE
Xdelta patch not applying

### ISSUE THREAD

**Issue by DragonQuestGamer** [cjuub/okaeri-chibi-translation#26]
I have tried many different xdelta patchers and after 5 hours of trying to apply the patch. It has said Patch Applied a few times, but then I Load up the game and its Still in Japanese? Is there any way you can send me a pre patched rom?

**Comment by cjuub** [comment]
How are you applying the patch? I assure you, there are no problems with the patch, so you must be doing something wrong.

And sorry, no I can not send a pre-patched rom since it is obviously illegal.

**Comment by DragonQuestGamer** [comment]
I figured you couldn't pre patch it, but I thought I'd ask anyway lol I have tried at least 3 different x delta patchers I select the patch and select the rom This is the most common error I get

![chibi error](https://cloud.githubusercontent.com/assets/19918066/16056297/7ab3d548-323a-11e6-9eda-1c78424ae912.png)

![patch applied](https://cloud.githubusercontent.com/assets/19918066/16057033/b0e69e72-323d-11e6-9950-ace40e95cb20.png)

Even when it is successfully applied I load up the game and it is still in Japanese

![4013 - okaeri chibi-robo happy rich oosouji tr jp high road __10616](https://cloud.githubusercontent.com/assets/19918066/16057131/2dffc604-323e-11e6-8006-58d4e99abd15.png)

**Comment by cjuub** [comment]
Did you try http://www.romhacking.net/utilities/598/ ?

I think you're using an old version of xdelta.exe, it needs to be version 3 (included in the above download).

Another thing you could try is to not use directory names with spaces in them, sometimes that causes issues.

**Comment by DragonQuestGamer** [comment]
The patch was successfully applied and the game is now translated into english! thanks for your help and it was was the xdelta patcher being outdated
